### ISSUE TITLE
Index Page with Navigation

### ISSUE THREAD

**Issue by Sijoma** [Skarlso/crd-to-sample-yaml#109]
It would be great if an index.html could be rendered that contains all the links to the generated CRD docs. 

In addition, it would be useful to always be able to navigate back to that page or have a navbar with a dropdown for the CRD selection.

**Comment by Skarlso** [comment]
Hello! Thanks for the issue! :)

> It would be great if an index.html could be rendered that contains all the links to the generated CRD docs.

I'm not a 100% sure I get this... links pointing to where? You mean the static rendering for `share` links like `https://crdtoyaml.com/share?url=https://raw.githubusercontent.com/Skarlso/crd-to-sample-yaml/main/sample-crd/infrastructure.cluster.x-k8s.io_awsclusters.yaml`?

> In addition, it would be useful to always be able to navigate back to that page or have a navbar with a dropdown for the CRD selection.

Yah, the top header if you click on the CRD thing it will load the frontpage. Arguably, that's not nice. :D I'm working on trying to refactor stuff and provide some kind of smoother navigation. That's a massive re-write though because I didn't have that in mind when I re-wrote the thing using go-dev.app.

About this bit:

>for the CRD selection.

CRD selection of previously visited crds you mean?

**Comment by Sijoma** [comment]
Maybe I should explain my use case a bit more. 

I want to use "cty" to render all the CRD docs to a folder in my private GitHub repository. Then use GitHub pages to allow users to discover them. Right now I create a "index.md" that links to all the CRD html. 

The problem then when using this is that you have to navigate back and forth to explore the CRDs. It's not a cohesive experience to see all CRDs of an Operator for example. 

Is that clearer? I will try and create an example in the next days. The tool is already great and very useful.

**Comment by Skarlso** [comment]
ah, so, create an index.html where you can select the appropriate CRD via a dropdown that you have parsed?

To be clear, these are the statically generated pages that you would like to somehow display from a drop-down?

**Comment by Sijoma** [comment]
> ah, so, create an index.html where you can select the appropriate CRD via a dropdown that you have parsed?
> 
> To be clear, these are the statically generated pages that you would like to somehow display from a drop-down?

Indeed yes. 

Here is an example where I manually created a "index" page: https://sijoma.github.io/camunda-autoscaling-hackday/
https://github.com/Sijoma/camunda-autoscaling-hackday/tree/main/docs

**Comment by Skarlso** [comment]
Gotcha, okay. Let me figure something out. :)

**Comment by Skarlso** [comment]
@Sijoma 

What would you think about something like this:

<img width="413" alt="Screenshot 2024-10-03 at 12 18 04" src="https://github.com/user-attachments/assets/82579a9b-4f0d-4258-b69e-4a86c55b5edf">

So all CRDs would be on the same page, but collapsed and they could be opened which would reveal all of the content normally on one page. Like, the samples, and the info and multiple versions.

**Comment by Sijoma** [comment]
Totally would fit my use case!

**Comment by Skarlso** [comment]
Noice! It's almost done actually. :D I'm just tweaking the output because I suck at HTML. :D

**Comment by Skarlso** [comment]
So this is what I have so far... I was wondering about what do you think if I leave a slot in there open for like, dynamic header configuration?

So you could run something like this:

```
./cty generate -r sample-crds --comments --format html -o index.html --include-header header.html
```

And it would take that header.html and insert it right before the collapsed crds. That way, you could configure some kind of header that would fit better. :) I don't know I have no skills in formatting :D 

<img width="1920" alt="Screenshot 2024-10-03 at 13 08 58" src="https://github.com/user-attachments/assets/0bee455f-039c-45f5-ae63-83f6396bdd66">

**Comment by Skarlso** [comment]
Ah, gonna skip the user provided html content thing. That's too much a security risk.. Since if someone gets ahold of the github action they could potentially inject bad code for your users.

I just gonna leave the user to tweak the site however they want if that's okay. :)

**Comment by Sijoma** [comment]
Awesome! Nice stuff. That was quick. ❤️ 

I think it's fine to iterate on it and the user also can still do other things with it. Should be easy to incorporate now. 

> any more suggestions for the output or something

Will do! I like that the tool is to simple & a CLI.

**Comment by Skarlso** [comment]
Thank you! :)))) Happy that you like it. :)
