### ISSUE TITLE
Idea/Feature Request: JSON schema generation from CRDs

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#115]
## Problem Statement
Currently, the tool is highly useful for generating example YAML files from Kubernetes Custom Resource Definitions (CRDs). However, many users also require JSON schemas for better integration with development environments. JSON schemas enable powerful features like auto-completion and validation in various IDEs through YAML plugins.

Generating these schemas manually using tools like `yq` is possible, but it can be cumbersome and non-intuitive, especially for new users. Integrating JSON schema generation directly into the tool would streamline this process and provide significant value.

## Proposed Solution
Enhance the current tool to include functionality that:

1. Automatically generates JSON schemas from CRDs.

## Benefits
- **Enhanced IDE Support:** Users can take advantage of auto-completion and schema validation, improving their overall development experience.
- **Time-Efficiency:** Simplifies and reduces the time needed to generate and utilize JSON schemas, especially for new users.
- **Consistency:** Ensures that the JSON schemas are always accurately derived from the CRDs, reducing the risk of errors.

## Conclusion
By adding JSONSchema generation to the tool, we can greatly enhance its functionality and provide users with a more powerful and intuitive development process. This feature would bridge the gap between CRD definitions and practical IDE integration, making the tool even more valuable.

What du you think @Skarlso

**Comment by Skarlso** [comment]
Hello!

Thanks for the writeup. :) I'm not opposed to it. CRD's OpenAPIV3Schema is already very close to a JSON Schema. I'm not a 100% sure it's a 1:1 convert... But let's see what we can do there. :)

**Comment by Skarlso** [comment]
For sure, but some fields have to be adjusted and the whole thing needs to be turned into JSON. :)

**Comment by Skarlso** [comment]
Well, this was easier than expected... :D
![Image](https://github.com/user-attachments/assets/ce101aa8-aa1b-4441-9ff5-07d6a3234c09)

**Comment by markussiebert** [comment]
Great!

**Comment by Skarlso** [comment]
Would this be okay, or did you imagine something else? https://github.com/Skarlso/crd-to-sample-yaml/pull/119

Basically a command that will generate the JSON Schema out of the CRD into a file. Nothing fancy really.

**Comment by markussiebert** [comment]
Just tried your code - the generated json schema worked! For me right now, sufficient :D

Things I found out:

- without specifying output, nothing happend (return code 0 - no error - but no file json schema generated)
- Global Options like format and minimal won't work I think, but are still present (of course they are global XD) - just somehow irritating...

**Comment by Skarlso** [comment]
Thanks for the feedback! 😊

**Comment by Skarlso** [comment]
Yeah I didn't implement any of the other flags

**Comment by Skarlso** [comment]
ok, v0.12.0 should contain the necessary command and flag fixes. :) Please feel free to open new issues with improvement ideas. :) Thank you for using cty! :))
