### ISSUE TITLE
Idea/Feature Request: Support for Generating Examples from CompositeResourceDefinitions (XRDs)

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#117]
## Problem Statement
While the tool currently offers valuable functionality for generating example YAML files from Kubernetes Custom Resource Definitions (CRDs), many users working within the Crossplane ecosystem require similar support for CompositeResourceDefinitions (XRDs).

XRDs are a core component of Crossplane, allowing users to define their own custom resources. Having the ability to generate example YAML files from XRDs would significantly enhance the tool's utility for Crossplane users, streamlining their development process and reducing manual effort.

## Proposed Solution
Extend the tool to include functionality that:
1. Automatically generates example YAML files from CompositeResourceDefinitions (XRDs). Maybe via autodetection?

This should be a relatively small change to implement, as XRDs essentially contain a CRD, with the OpenAPI part being identical. Therefore, the existing logic for CRDs can be reused with minor adjustments to accommodate the XRD-specific structures.

## Benefits
- **Broader Utility:** Expands the tool's applicability to the Crossplane community, supporting a broader range of Kubernetes users.
- **Increased Productivity:** Simplifies the creation of example YAMLs for XRDs, saving users time and effort.
- **Seamless Integration:** Provides a consistent approach and toolset for generating examples from both CRDs and XRDs, enhancing the overall user experience.
- **Unique Offering:** As of now, I have not found any other tool that provides this functionality.
- **Minimal Effort Required:** Since XRDs include parts of a CRD with an identical OpenAPI part, implementing this feature would involve minor adjustments to the existing logic, making it a relatively small and straightforward change.

## Conclusion
By adding support for generating example YAMLs from CompositeResourceDefinitions (XRDs), we can significantly broaden the tool's appeal and utility. This feature would be a valuable addition, catering specifically to users within the Crossplane ecosystem and improving their workflow efficiency. Implementing this change should be relatively straightforward given the similarities between CRDs and XRDs.

What do you think?

**Comment by Skarlso** [comment]
Sure! 👍

**Comment by Skarlso** [comment]
Actually, because go is typed, this is not straight-forward. I'll have to convert everything to map[string]any in order to support other types that have schema's in them.

It would make things easier if I would know that your embedded openAPIV3Schema type is at least of type `v1beta1.JSONSchemaProps` defined here: [v1beta1.JSONSchemaProps](https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/v1beta1/types_jsonschema.go). If not than this is gonna be a lot of headache to take care of.

**Comment by Skarlso** [comment]
So... nevermind, I just "solved" it by creating my own type and marshalling into that. That should work. :)

**Comment by Skarlso** [comment]
<img width="1431" alt="Screenshot 2024-10-14 at 17 46 41" src="https://github.com/user-attachments/assets/d00b1e9d-ab2b-4949-9e3d-e58a48d518c3">

**Comment by Skarlso** [comment]
So, once v1.0.0 is released, you should be able to use any kind of type as long as it follows a certain format, which XRD does by the looks of it.

Good luck, please tell me if you find any problems. :)
