### ISSUE TITLE
Bug: File already closed when generating html

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#122]
Hi,

I encountered an issue while running the following command:

```bash
cty generate crd -c ./dist/crd-xdxcproject-c8e89137.k8s.yaml -o ./docs/html/crd-xdxcproject-c8e89137.html -f html
```

The command outputs the following error:

```bash
failed to close output file: close ./docs/html/crd-xdxcproject-c8e89137.html: file already closed
```

It seems there might be an issue with file handling, as the error suggests the file is already closed. However, the return code is 0, indicating the operation is "OK".

Just wanted to bring this to your attention.

---

**Comment by Skarlso** [comment]
Ah yeah. Because I'm closing it in Render already 🤦 

Also, this was just an error to the output in a defer, not a failure. :) Thanks. :)
