### ISSUE TITLE
generate crd --no-random does not work for html output

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#124]
Hi,

experiencing issues with --no-random. This flags does not work anymore :-)

**Comment by Skarlso** [comment]
Goddamn :D Thanks, I'll investigate. :)

**Comment by markussiebert** [comment]
no sorry - i am wrong

**Comment by markussiebert** [comment]
My fault - forgotten to use it with html option

**Comment by markussiebert** [comment]
Ok .. clarification. --no-random is not working for html output

**Comment by Skarlso** [comment]
Awesome, thanks. It's probably ignored 🤦

**Comment by Skarlso** [comment]
Should be fixed and released now :)
