### ISSUE TITLE
Idea/FeatureRequest: Extend JSON Schemas with "x-kubernetes-group-version-kind" Property

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#128]
I use cty to generate JSON schemas from my CRDs. To enhance compatibility and potentially improve IDE integrations, it would be beneficial to extend the generated JSON schemas with the `"x-kubernetes-group-version-kind"` property, as shown in [this example](https://github.com/instrumenta/kubernetes-json-schema/blob/133f84871ccf6a7a7d422cc40e308ae1c044c2ab/v1.7.8/clusterrole.json#L6C3-L6C36).

### Extend JSON Schemas

It would be great if the generated JSON schemas could be extended with the `"x-kubernetes-group-version-kind"` property. This property provides information about the API group, version, and kind, which may be useful for tools and IDE integrations that utilize these schemas.

### Context and Clarification

I was investigating Kubernetes JSON schemas because I didn't understand why my autocompletion was not completing the GroupVersionKind (GVK) in my IDE. It appears that some IDE integrations might rely on the `"x-kubernetes-group-version-kind"` property for proper functionality. However, I may be mistaken and it might be something that needs to be defined within my CRDs instead.

## Potential Benefits

- Enhanced compatibility with existing tools and IDE integrations.
- Improved schema utility for developers who rely on JSON schemas for validation and code generation.
- Better metadata representation within the JSON schemas, providing more context and information.

I think this should be easy to implement ...

**Comment by Skarlso** [comment]
Oh nice catch. Yeah, I can add that.
