### ISSUE TITLE
FeatureRequest: Package external dependencies

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#130]
In the html file, there are external stylesheets:

![image](https://github.com/user-attachments/assets/87291067-d7a2-4f93-98f8-564126977355)

might it be possible to package them inside cty and don't download them from cdn? cty could place them next to the html.

**Comment by Skarlso** [comment]
There was a request in the early days NOT to package these. :D So now I'm not sure what to do :P

**Comment by markussiebert** [comment]
I would say definitiv not use cdn :-)

On the pro side, there is convenience and clean code, but there are several reasons for not using cdns:

Privacy and Security Concerns:
- User Tracking: Utilizing a CDN could potentially expose user data to third parties who own the CDN infrastructure, leading to privacy issues.
- Attacks: If a CDN is compromised, stylesheets could be altered to include malicious code. (

Dependency on Third Party:
- Reliability: Your website's styling is dependent on the availability of the external CDN. If the CDN goes down or the stylesheet is deleted, your site might not load properly.
- Accesess: You need to have access to the cdn - might be restricted by Proxy-Servers.

Compliance and Legal Issues:
- GDPR and Other Regulations: Depending on the data protection regulations in your region (like GDPR), sending user requests to third-party servers might complicate compliance.

**Comment by Skarlso** [comment]
Alrighty then :)

**Comment by Skarlso** [comment]
I'll do this next. :D

**Comment by Skarlso** [comment]
The way we can do this is that I inline the CSS into the page, otherwise, you'd have to have some kind of webserver which would defeat the purpose of having a single static website.

**Comment by Skarlso** [comment]
Generated a 275Kb index page. It's not THAT bad... :D
