### ISSUE TITLE
`bool`s and `int`s are translated with actual values

### ISSUE THREAD

**Issue by Callisto13** [Skarlso/crd-to-sample-yaml#15]
When the value type is a `string` or `[]string`, it is represented in the translated yaml as `"string"`.

When the types are `bool` or `int`, there are actual values `true` and `1`, rather than types

**Comment by Skarlso** [comment]
Is... that a problem? :D I mean, I'm providing a value based on the type, so "string" signifies a string value.

Alternatively, I can set the name of the type as well I guess 🤔. I though providing type default values would be neat. :D

**Comment by Callisto13** [comment]
> I'm providing a value based on the type, so "string" signifies a string value.

ah yeh true

>  though providing type default values would be neat.

or dangerous

```yaml
disableAllSecurity: true
```

😉 😂 

but i think you are right

**Comment by Skarlso** [comment]
Cool. :D Also, eventually, what I'm planning on doing is actually providing a value that conforms to any restriction provided, such as format or pattern. Though that might be even more dangerous maybe. :D
