### ISSUE TITLE
Write some frigging tests

### ISSUE THREAD

**Issue by Skarlso** [Skarlso/crd-to-sample-yaml#22]
Honestly. This is embarrassing.

**Comment by Callisto13** [comment]
i'm embarrassed to know you tbh

**Comment by Callisto13** [comment]
i suppose i could occasionally contribute, rather than spamming you with feature requests and insults

**Comment by Skarlso** [comment]
Yes, that sounds lovely. :D

**Comment by Skarlso** [comment]
I wrote some frigging tests.

**Comment by Callisto13** [comment]
yay we can be friends again
