### ISSUE TITLE
how get those nice rendered website?

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#58]
Hi,
could you provider some sample docs on how to generate those nice looking html for the crds? Is it possible to generate them as static files for use in github pages and so on?

 I would like to generate static files for my crds - is this possible?

Something like

make static path/to/my/crd.yaml

**Comment by Skarlso** [comment]
I'm thinking about this. :D I still have the old templates, so I guess I can try to achieve something with them.

**Comment by Skarlso** [comment]
I'm using the old design simply because it's convenient for now. I might update it to the latest one, but honestly, this looks smoother hahahahaha.

Thanks for the suggestion @markussiebert :)

**Comment by markussiebert** [comment]
So great! So glad that I found this wonderful project!

**Comment by Skarlso** [comment]
Thank you! 🙏😊
