### ISSUE TITLE
Idea: add flag to generate "minimal" examples, only containing required values

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#70]
I have another Idea. It would be great if there were a flag to only generate minimalistic examples, containing only flags that are required, not optional ones.

There are two use cases:

- For users we could provide minimal working examples
- We could generate Testvalues for testing defaults/unset values

**Comment by Skarlso** [comment]
Sure, sounds great! I'll add it. :) Would you also want to see that on the website? 🤔

**Comment by markussiebert** [comment]
> Sure, sounds great! I'll add it. :) Would you also want to see that on the website? 🤔
> 
> _Edit_: I guess that's easy to add really. I'm just gonna add another checkbox. :D
> 
> _Edit2_: This gives me a good opportunity to refactor a bit because the parameter list is getting ridiculous hahahaha.

Cool thank you!

For the website it's not that important - but why not :-)

**Comment by Skarlso** [comment]
@markussiebert 👋 Would you mind trying v0.5.0 and see if it works as requested? :)

**Comment by markussiebert** [comment]
Great Job! Works just like I expected - Amazing!

**Comment by Skarlso** [comment]
Nice! Thanks for the suggestion! :) I'll adjust the website at some point. :D For now, it's not supporting this hehe.
