### ISSUE TITLE
feat: version command that prints the current version

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#73]
Hi, 
now I am trying to automate the update process of cty and there it would be great if I could check if the installed cty version is the correct one. But I didn't found any version information - so something like ```cty version``` would be great ;-)

Sorry if I have so many ideas - at the moment your tool is just the best I found for generating examples :)

Maybe I could implement this - my go is not so fluent XD

**Comment by Skarlso** [comment]
No worries at all! You're right. I need to add a `version` part. I'll update the release process to add in the tag and build it with that. :)

**Comment by markussiebert** [comment]
Great!

**Comment by Skarlso** [comment]
Closing this as done. Please feel free to re-open if anything is still missing. :) Thank you! 🙇
